// Code generated by protoc-gen-go-rest. DO NOT EDIT.
// versions:
// - protoc-gen-go-rest v0.0.0-alpha.0
// - protoc             v3.21.12
// source: example/proto/example.proto

package api

import (
	embed "embed"
)

//go:embed example_swagger.json
var swaggerFile embed.FS

func GetExampleSwagger() []byte {
	js, err := swaggerFile.ReadFile("example_swagger.json")
	if err != nil {
		return []byte("{}")
	}

	return js
}
