// Code generated by protoc-gen-go-oapi. DO NOT EDIT.
// versions:
// - protoc-gen-go-oapi v0.0.0-alpha.0
// - protoc             v3.21.12
// source: example/proto/example.proto

package api

import (
	runtime "github.com/merzzzl/proto-rest-api/runtime"
	swagger "github.com/merzzzl/proto-rest-api/swagger"
	http "net/http"
	strings "strings"
)

import _ "embed"

//go:embed example_oapi.json
var swaggerJSON []byte

// RegisterSwaggerUIHandler registers swagger ui handler.
func RegisterSwaggerUIHandler(mux runtime.ServeMuxer, path string) error {
	if !strings.HasPrefix(path, "/") {
		path = "/" + path
	}

	if !strings.HasSuffix(path, "/") {
		path += "/"
	}

	fs, err := swagger.GetSwaggerUI(swaggerJSON, path)
	if err != nil {
		return err
	}

	mux.Handle(path, http.FileServer(fs))

	return nil
}

// RegisterReDocUIHandler registers redoc ui handler.
func RegisterReDocUIHandler(mux runtime.ServeMuxer, path string) error {
	if !strings.HasPrefix(path, "/") {
		path = "/" + path
	}

	if !strings.HasSuffix(path, "/") {
		path += "/"
	}

	fs, err := swagger.GetReDocUI(swaggerJSON, path)
	if err != nil {
		return err
	}

	mux.Handle(path, http.FileServer(fs))

	return nil
}
